[build]
  command = "CI=false yarn build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.17.0"
  YARN_VERSION = "1.22.19"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 